apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: A
  name: A
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 400Mi  
    name: A
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
