apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: B
  name: B
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi  
    name: B
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
