apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: C
  name: C
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 400Mi  
    name: C
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
